[WIP] Add Support for BPF in capstone-rs
capstone-rust/capstone-rs pull request #144
Opened 2023-09-10 04:10 UTC by deepaksirone

Hello,

Thanks for maintaining this project. This PR adds support for BPF in capstone-rs. I regenerated the bindings in capstone-sys using a newer version of bindgen in Cargo.toml since it did not work with clang-16. I am yet to write some tests for the implementation. Please let me know if I am on the right track with this or if I am missing something! :-)

2023-09-17 01:38 UTC, tmfink commented
Thank you for the contribution! I'll take a look at your changes.

2023-09-17 03:04 UTC, tmfink requested changes
Overall the changes look good, but please also add tests in `capstone-rs/src/test.rs`.
You can find tests by building/running `capstone-sys/capstone/tests/test_bpf.c`.

2023-09-17 03:04 UTC, tmfink commented on capstone-sys/pre_generated/capstone_archs_impl.rs
Please read through the directions in `capstone-sys/pre_generated/update-bindings.md`; it looks like this file is unformatted

2023-09-17 03:07 UTC, tmfink commented
Aside from my  comments, I may want to wait to merge this until #143 is merged since that's a big change and there would be conflicts.

@Lancern do you have any opinions?

2023-09-17 07:11 UTC, Lancern commented
> Aside from my comments, I may want to wait to merge this until #143 is merged since that's a big change and there would be conflicts.
> 
> @Lancern do you have any opinions?

The BPF arch added in this PR looks good and it should be easy to merge it with my PR. If you decide that this PR lands after my PR, I'll try finish my PR quickly.

2023-09-18 03:52 UTC, tmfink commented
> The BPF arch added in this PR looks good and it should be easy to merge it with my PR. If you decide that this PR lands after my PR, I'll try finish my PR quickly.

@Lancern If you're fine handling any conflicts, then I'll just "merge" whichever PR is ready first.

Also, please don't literally `git merge`. Instead, please maintain linear history with something like `git rebase -i`.

2023-10-15 15:26 UTC, deepaksirone commented
Hi @tmfink, I have added some tests and fixed the formatting of the generated files.

2023-10-16 05:40 UTC, tmfink requested changes
After making the changes, please run `cargo fmt` to format the entire repo.

2023-10-16 05:40 UTC, tmfink commented on capstone-rs/src/test.rs
> +fn test_ebpf() {
Also add a test function `test_arch_bpf_detail()` that tests the details for each instruction. These `test_arch_*_detail()` tests catch a lot of bugs and changes in behavior when we upgrade the C library. For an example, see `test_arch_x86_detail()`:
   https://github.com/capstone-rust/capstone-rs/blob/7c9a51f6eb81709cde1de7f7498a0e16f29bd852/capstone-rs/src/test.rs#L2681

2024-04-07 09:41 UTC, chengshuyi commented
Hi, are there any plans to merge this PR? I look forward to using this feature. Thanks.

2024-04-07 17:32 UTC, deepaksirone commented
Hi @tmfink and @chengshuyi I have added the tests requested. Please let me know if there are any more changes needed

2024-04-13 06:21 UTC, tmfink approved these changes
minor issues; I'll clean them up

2024-04-13 06:21 UTC, tmfink commented on capstone-rs/src/arch/mod.rs
> +                /// Returns the XCore details, if any
copy/paste error: mention BPF instead of Xcore

2024-04-13 06:21 UTC, tmfink commented on capstone-rs/src/test.rs
> +            assert!(false);
just call `panic!()` instead

2024-04-13 06:21 UTC, tmfink commented on capstone-rs/src/test.rs
> +            assert!(false);
panic!() instead

2024-04-13 06:23 UTC, merged

2024-04-13 06:24 UTC, tmfink commented
Thanks for the PR!
I'll do some minor clean-up myself

2024-04-13 06:27 UTC, tmfink commented
Did some minor clean-up w/ 38bbcce944e42a44638f99489b669f4516cd7001